from setuptools import setup

setup(
    name="glyphviewer",
    version="0.9",
    description="A Django app for examining web fonts and the characters they contain.",
    author="Peter Murphy",
    author_email="peterkmurphy@gmail.com",
    url="http://pypi.python.org/pypi/glyphviewer/",
    packages=["glyphviewer", "glyphviewer.templatetags"],
    package_data={
        "glyphviewer": [
            "templates/glyphviewer/*.html",
            "static/glyphviewer/*.css",
            "static/glyphviewer/fonts/*.woff",
        ],
    },
    keywords="font glyph web woff ttf otf TrueType OpenType Django",
    license="BSD-3-Clause",
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Other Environment",
        "Environment :: Web Environment",
        "Framework :: Django",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: End Users/Desktop",
        "Intended Audience :: Other Audience",
        "License :: OSI Approved :: BSD License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
        "Operating System :: OS Independent",
        "Operating System :: MacOS",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: POSIX",
        "Topic :: Artistic Software",
        "Topic :: Education",
        "Topic :: System :: Console Fonts",
        "Topic :: Text Processing :: Fonts",
        "Topic :: Text Processing :: Linguistic",
        "Topic :: Utilities",
    ],
    long_description=open("README.md", encoding="utf-8").read(),  # noqa: SIM115
    long_description_content_type="text/markdown",
    install_requires=[
        "Django >= 5.2",
        "fonttools >= 4.0",
        "numpy >= 2.0",
        "brotli >= 1.0",
        "chardet >= 7.0",
    ],
)
